ALTER TABLE zesto_players ADD COLUMN IF NOT EXISTS wood INTEGER NOT NULL DEFAULT 0;
ALTER TABLE zesto_players ADD COLUMN IF NOT EXISTS stone INTEGER NOT NULL DEFAULT 0;
ALTER TABLE zesto_players ADD COLUMN IF NOT EXISTS ore INTEGER NOT NULL DEFAULT 0;
ALTER TABLE zesto_players ADD COLUMN IF NOT EXISTS ingots INTEGER NOT NULL DEFAULT 0;
ALTER TABLE zesto_players ADD COLUMN IF NOT EXISTS energy INTEGER NOT NULL DEFAULT 30;
ALTER TABLE zesto_players ADD COLUMN IF NOT EXISTS energy_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE zesto_players ADD COLUMN IF NOT EXISTS streak INTEGER NOT NULL DEFAULT 0;
ALTER TABLE zesto_players ADD COLUMN IF NOT EXISTS last_checkin DATE;

CREATE TABLE IF NOT EXISTS zesto_buildings (wallet TEXT NOT NULL, kind TEXT NOT NULL, level INTEGER NOT NULL DEFAULT 1, built_at TIMESTAMPTZ NOT NULL DEFAULT now(), collected_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY (wallet, kind));
CREATE TABLE IF NOT EXISTS zesto_tools (wallet TEXT NOT NULL, tool TEXT NOT NULL, crafted_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY (wallet, tool));
CREATE TABLE IF NOT EXISTS zesto_points_log (id SERIAL PRIMARY KEY, wallet TEXT NOT NULL, source TEXT NOT NULL, points INTEGER NOT NULL, detail TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS zesto_points_log_wallet_idx ON zesto_points_log (wallet, created_at DESC);
CREATE TABLE IF NOT EXISTS zesto_sessions (token_hash TEXT PRIMARY KEY, wallet TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS zesto_nonces (wallet TEXT PRIMARY KEY, nonce TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL);

CREATE TABLE IF NOT EXISTS zesto_progress (wallet TEXT NOT NULL, metric TEXT NOT NULL, period TEXT NOT NULL, amount INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (wallet, metric, period));
CREATE TABLE IF NOT EXISTS zesto_quest_claims (wallet TEXT NOT NULL, quest_id TEXT NOT NULL, period TEXT NOT NULL, claimed_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY (wallet, quest_id, period));
